name : hellow-world
on: push
jobs: 
  hello-word-job:
    runs-on: ubuntu-latest
    steps:
    - name: Check our repository code
      uses: actions/checkout@v3
    - run:  echo "$(cat hello_world.text)"  
